
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jflex_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 3;
  public static final int MAS = 4;
  public static final int error = 1;
  public static final int IGUAL = 6;
  public static final int MENOS = 5;
  public static final int PCOMA = 2;
  public static final int EOF = 0;
  public static final int ENTERO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PCOMA",
  "ID",
  "MAS",
  "MENOS",
  "IGUAL",
  "ENTERO"
  };
}

